# Generated by Django 2.0 on 2019-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
