# Generated by Django 2.0 on 2019-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
