# Generated by Django 2.0 on 2019-03-06 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_hash', models.TextField()),
                ('block_number', models.PositiveIntegerField()),
                ('from_address', models.CharField(max_length=64)),
                ('gas', models.PositiveIntegerField()),
                ('gas_price', models.DecimalField(decimal_places=0, max_digits=50)),
                ('tx_hash', models.TextField()),
                ('tx_input', models.TextField()),
                ('nonce', models.PositiveIntegerField()),
                ('to_address', models.CharField(max_length=64)),
                ('transaction_index', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=0, max_digits=50)),
                ('has_data', models.BooleanField()),
                ('is_token', models.BooleanField()),
                ('token_amount', models.DecimalField(decimal_places=0, max_digits=50)),
                ('token_to', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('notify_email', models.CharField(blank=True, max_length=128, null=True)),
                ('watched_address', models.CharField(max_length=64)),
                ('notify_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('watch_token_transfers', models.BooleanField(default=False)),
                ('summary_notifications', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subscribedtransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.Subscription'),
        ),
    ]
