# Generated by Django 2.0 on 2019-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='notify_sms',
        ),
        migrations.AddField(
            model_name='subscription',
            name='notify_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
