# Generated by Django 2.0 on 2019-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedtransaction',
            options={'ordering': ('-created_at',)},
        ),
    ]
