# Generated by Django 2.0 on 2019-03-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190304_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.TextField()),
                ('block_number', models.CharField(max_length=64)),
                ('from_address', models.CharField(max_length=64)),
                ('gas', models.CharField(max_length=64)),
                ('gas_price', models.CharField(max_length=64)),
                ('tx_hash', models.TextField()),
                ('tx_input', models.TextField()),
                ('nonce', models.CharField(max_length=64)),
                ('to_address', models.CharField(max_length=64)),
                ('transaction_index', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('has_data', models.BooleanField()),
                ('is_token', models.BooleanField()),
                ('token_amount', models.CharField(max_length=64)),
                ('token_to', models.CharField(max_length=64)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription')),
            ],
        ),
    ]
