# Generated by Django 2.0 on 2019-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20190404_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='include_pricing_data',
            field=models.BooleanField(default=False),
        ),
    ]
