# Generated by Django 2.0 on 2019-04-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_pricelookup_currency'),
        ('subscriptions', '0004_subscription_include_pricing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedtransaction',
            name='price_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.PriceLookup'),
        ),
    ]
