# Generated by Django 2.0 on 2019-03-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='watch_token_transfers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscribedtransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.Subscription'),
        ),
    ]
