# Generated by Django 2.0 on 2019-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscribedtransaction_price_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
