# Generated by Django 2.0 on 2019-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20190304_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='watch_token_transfers',
            field=models.BooleanField(default=False),
        ),
    ]
