# Generated by Django 2.0 on 2019-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20190304_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='subscription',
            name='summary_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
