# Generated by Django 2.0 on 2019-03-05 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20190305_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
