# Generated by Django 2.0 on 2019-02-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=255)),
                ('latest_block', models.PositiveIntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='networks.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
