# Generated by Django 2.0 on 2019-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_scanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
