# Generated by Django 2.0 on 2019-03-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apicredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paused', 'paused')], default='active', max_length=10),
        ),
    ]
