# Generated by Django 2.0 on 2019-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190329_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='nickname',
            field=models.CharField(default='empty', max_length=64),
            preserve_default=False,
        ),
    ]
