version: '2.1'
services:
  psql:
    image: sameersbn/postgresql:9.6-2
#    expose:
#      - '5432'
    ports:
    - "5432:5432"
    environment:
      DB_NAME: tritium
      DB_PASS: tritium
      DB_USER: tritium
    volumes:
      - /data/txgun/tritium/postgresql:/var/lib/postgresql

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    extends:
      service: tritium-django-dev
      file: build.yml
    volumes:
      - ../:/app
    links:
      - psql
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=django_shell
      -  DATABASE_URL=psql://tritium:qjCSc6Atc5EN6N2@txgun-tritium-beta.cnu1x1c3g09o.us-east-2.rds.amazonaws.com/tritium
    command: "bash"
    entrypoint: []

  runserver:
    extends:
      service: tritium-django-dev
      file: build.yml
    command: ["python", "manage.py", "runserver_plus", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    links:
      - psql
    volumes:
      - ../:/app
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=runserver

